services:
  - type: web
    name: telegram-video-bot
    env: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: OWNER_ID
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: video-storage
      mountPath: /app/downloads
      sizeGB: 1