services:
  - type: web
    name: vault-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false   # set in Render dashboard
      - key: OWNER_ID
        sync: false
      - key: UPLOAD_CHANNEL_ID
        sync: false
      - key: DB_CHANNEL_ID
        sync: false
      - key: DB_PATH
        value: "/data/database.sqlite3"
      - key: JOB_DB_PATH
        value: "/data/jobs.sqlite"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "INFO"
      - key: BROADCAST_CONCURRENCY
        value: "12"
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: true
